# Generated by Django 4.0.3 on 2022-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcountry', models.CharField(blank=True, max_length=100)),
                ('itemcity', models.CharField(blank=True, max_length=100)),
                ('itemcinema', models.CharField(blank=True, max_length=100)),
                ('itemgate', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=100)),
                ('itememail', models.CharField(blank=True, max_length=100)),
                ('itemmobile', models.CharField(blank=True, max_length=100)),
                ('itempayment', models.CharField(blank=True, max_length=100)),
                ('itemwallet', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FilmRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cphile_name', models.CharField(blank=True, max_length=100)),
                ('cphile_email', models.CharField(blank=True, max_length=100)),
                ('cphile_title', models.CharField(blank=True, max_length=100)),
                ('cphile_director', models.CharField(blank=True, max_length=100)),
                ('cphile_genre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemmovie', models.CharField(blank=True, max_length=100)),
                ('itemdate', models.CharField(blank=True, max_length=100)),
                ('itemtime', models.TimeField(blank=True)),
                ('itemtickets', models.CharField(blank=True, max_length=100)),
                ('itemdateres', models.DateField(blank=True)),
                ('itemtimeres', models.TimeField(blank=True)),
            ],
        ),
    ]
