# Generated by Django 4.0.3 on 2022-07-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plklsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='itemtime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
